---
title: "Welcome to the CWIP App"
author: "Version 2.22"
output:
  html_fragment:
     includes:
       before_body: header.html
---

<!-- <div class="mycontent"> -->

<br>

<div style = "padding: 0px 20%; font-size: 16px"> 

Last updated: 19.05.2023. Current longitudinal data between 2010 and 2022.

**Welcome to the CWIP App.** The purpose of the CWIP App is to make it easier for the public to interrogate longitudinal and spatial data related to children's services and society in general. It brings together a range of data sources, combines them together, and visualises them for the user. It includes data on children's services expenditure, rates of intervention, poverty, average local authority households income, indices of deprivation, and more. It allows to you perform a range of statistical analyses, such as adjusting values for underlying deprivarion, performing cluster analysis, and generating some descriptive statistics.

As with all online tools that merge and manipulate data, you should only use the CWIP App for reporting figures **at your own risk**. While I have tried to be [as transparent as possible about all of the data sources and any transformations I have made](https://github.com/cjrwebb/cwip-app/blob/master/data/data-tidying.R), there is always a risk that someone else would disagree with choices made around adjustments for inflation, population denominators, and the comparability over time of certain measures. 

---

**Feedback and citation**

Please submit any feedback, questions, and bugs to <a href = "mailto:c.j.webb@sheffield.ac.uk">c.j.webb@sheffield.ac.uk</a>, or [log an issue on Github](https://github.com/cjrwebb/cwip-app). Please check the Issues section below to see if the issue you're reporting has already been submitted.

Please cite the CWIP App as *Webb, C. & Thomas, R. (2020). The Child Welfare Inequalities Project App. www.cwip-app.co.uk*. Please email me with any details on how you have used the CWIP App, this way I can evidence its impact and justify future funding.

---

**Background on CWIP**

To read the full report about the findings from the Child Welfare Inequalities Project and other outputs, [click here](https://www.nuffieldfoundation.org/project/inequalities-in-child-welfare-intervention-rates). This report frames the theoretical and academic interpretation of many features in children's services data. You may also benefit from reading the final report from Rick Hood, et al.'s Nuffield Foundation funded project: ["Identifying and understanding the link between system conditions and welfare inequalities in children’s social care services"](https://www.healthcare.ac.uk/wp-content/uploads/2020/04/System-conditions-and-inequalities_Full-report_Final_March-2020.pdf).


---

**Data Sources**

All data has been sourced from public government data releases. The [github repository](https://github.com/cjrwebb/cwip-app) contains the full data tidying code which links directly to all of the source data, which includes details of the web source pages in each directory. Most data has been transformed, aggregated or disaggregated in some way, by me and where descriptions try to be as clear as possible. You should use caution and double-check any rates, make use of the most up-to-date data (including any revisions or non-provisional releases), and the internal calculations if using them to inform a critical decision. The full list of sources includes:

* Data from the Department for Education: 
  * Children in Need Census
  * Children looked-after statistics
  * Section 251 Returns
  * SEN Statements and EHCP Plan Statistics
* Data from the Office of National Statistics and Nomis (Census and Population estimates)
* Indices of Multiple Deprivation 2019 and 2015
* Earnings and hours worked estimates by place of residence (ONS)
* Revenue Outturns data
* 2011 Census relating to Ethnicity
* Life Expectancy at Birth (2009-2013)
* Median House Price (2017 & 2018)
* Journey Time Statistics for Key Services (2017)
* Access to Healthy Assets and Hazards (AHAH) 2017
* StatsWales
* Northern Ireland Statistics and Research Agency
* Northern Ireland Indices of Multiple Deprivation 2017
* Scottish Indices of Multiple Deprivation & Indicators 2020
* Scottish Census Data (2011)


---

**Funding and Acknowledgements**

The creation and maintenence of this app has been supported by grants from the ESRC (Impact Accelerator Account), the Nuffield Foundation, and the British Academy.

It was only possible to create this app thanks to the people behind R Shiny, RStudio, as well as many other R package authors and the wider community. The code was written by me, and is not the highest quality, as I am not a programmer/data scientist (and in many ways this is testament to how amazing R, Shiny, the tidyverse and the R community is). All code used to read data sources, calculate transformations, program the app, and the data itself is available on Github: [https://github.com/cjrwebb/cwip-app](https://github.com/cjrwebb/cwip-app)


---

<b>List of Issues (Current and Solved)</b>

<details>
<summary>Click to show issues</summary>

* <strike>Cannot install waffle plots from github using `devtools::install_github`, which prevents installing `waffle` > 0.7.0 for spending waffle plots. Temporarily hidden spending waffle plots. </strike> SOLVED BY CHANGING `Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")`

* <strike>Fixed Waffle plots, but cannot display these in Shiny app. Problem with Font Awesome 5 library or with waffle package? Can't see immediate fix and will wait until waffle > 0.70 is on CRAN.</strike> Fixed by installing fonts to .fonts on shinyapps.io deployment.

* England Average label on trendplots can occasionally obscure LA label.

* Add additional filter to remove Isles of Scilly and City of London from some data

</details>


</div>

<br><br><br><br><br>